import "@styles/globals.scss";
import "@styles/variables.scss";
import { manrope, dmSerifText } from "@config/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${dmSerifText.variable} font-manrope antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
